name: Avci Otomasyonu

on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir çalışır
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  av-zamani:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Kur
        run: pip install requests

      - name: Avciyi Calistir
        run: python avci.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name 'Avci-Bot'
          git config --global user.email 'avci@bot.com'
          git add avci_listesi.m3u
          git commit -m "Ganimetler guncellendi: $(date +'%d-%m-%Y %H:%M')" || echo "Degisiklik yok"
          git push
