name: ğŸ¦… Avci Operasyonu

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  av-zamani:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Depoyu Kontrol Et
        uses: actions/checkout@v3

      - name: ğŸ Python Sistemini HazÄ±rla
        # HATA BURADAYDI: BaÅŸÄ±na 'actions/' eklendi
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: ğŸ“¦ Gerekli AraÃ§larÄ± Kur
        run: pip install requests

      - name: ğŸ¹ AvcÄ±yÄ± Sahaya GÃ¶nder
        run: python avci.py

      - name: ğŸ† Ganimetleri Kaydet
        run: |
          git config --global user.name 'Avci-Bot'
          git config --global user.email 'avci@bot.com'
          git add avci_listesi.m3u
          git commit -m "ğŸ¦… Ganimetler GÃ¼ncellendi: $(date +'%d-%m-%Y %H:%M')" || echo "Yeni ganimet yok."
          git push
