name: Avci Otomasyonu

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  av-zamani:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Kur
        run: pip install requests

      - name: Avciyi Calistir
        run: python avci.py

      - name: Degisiklikleri Kaydet ve Pushla
        run: |
          git config --global user.name 'Avci-Bot'
          git config --global user.email 'avci@bot.com'
          
          # HATA ÇÖZÜMÜ BURADA:
          git add avci_listesi.m3u
          git stash                          # Değişiklikleri hafızaya al
          git pull origin main --rebase      # Güncel kodu çek
          git stash pop || echo "Geri alacak bir şey yok" # Değişiklikleri geri yükle
          
          # Kaydet ve Gönder
          git add avci_listesi.m3u
          git commit -m "Ganimetler guncellendi: $(date +'%d-%m-%Y %H:%M')" || echo "Degisiklik yok"
          git push origin main
