name: IPTV Otomatik Guncelleyici

on:
  schedule:
    # Her saatin basında çalışır
    - cron: '0 * * * *'
  workflow_dispatch: # Elle tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Depoyu cek
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Bagimliliklari Yukle
      run: |
        pip install selenium webdriver-manager

    - name: Scripti Calistir
      run: python update_link.py

    - name: Degisiklikleri Kaydet
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add listem.m3u
        git commit -m "Saatlik Guncelleme: $(date)" || exit 0
        git push
