name: Linkleri Guncelle
on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch: # Elle başlatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Modulleri Yukle
        run: pip install requests
      - name: Botu Calistir
        run: python bot.py
      - name: Listeyi Kaydet
        run: |
          git config --global user.name 'GitHub Bot'
          git config --global user.email 'bot@github.com'
          git add *.m3u
          git commit -m "Otomatik guncelleme" || exit 0
          git push
