name: IPTV Otomatik Guncelleyici

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı
  workflow_dispatch: # Manuel çalıştırma

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub'a dosyayı geri kaydetmesi için zorunlu izin
      
    steps:
    - name: Depoyu cek
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Bagimliliklari Yukle
      run: |
        pip install selenium webdriver-manager

    - name: Scripti Calistir
      run: python update_link.py

    - name: Degisiklikleri Kaydet
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Dosya oluştuysa takip listesine ekle
        if [ -f listem.m3u ]; then
          git add listem.m3u
          # Değişiklik yoksa hata vermeden bitir
          git diff --staged --quiet || (git commit -m "Saatlik Guncelleme: $(date)" && git push)
        else
          echo "Hata: listem.m3u dosyası Python tarafından oluşturulamadı!"
          exit 1
        fi
